import { useState } from "react";
import { Button, Card, Col, Form, Row, Alert } from "react-bootstrap";
import { Link } from "react-router";
import type { RegisterRequest } from "../types";
interface RegisterFormProps { onSubmit: (data: RegisterRequest) => Promise<void>; loading?: boolean }
export default function RegisterForm({ onSubmit, loading = false }: RegisterFormProps) {
  const [form, setForm] = useState<RegisterRequest>({ firstName: "", lastName: "", phone: "", email: "", password: "", confirmPassword: "" });
  const [errors, setErrors] = useState<string[]>([]);
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [e.target.name]: e.target.value });
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); const next: string[] = []; if (form.password.length < 8) next.push("Password must be at least 8 characters."); if (!/[A-Z]/.test(form.password)) next.push("Password must contain at least one uppercase letter."); if (!/[a-z]/.test(form.password)) next.push("Password must contain at least one lowercase letter."); if (!/\d/.test(form.password)) next.push("Password must contain at least one number."); if (!/[!@#$%^&*(),.?\":{}|<>]/.test(form.password)) next.push("Password must contain at least one special character."); if (form.password !== form.confirmPassword) next.push("Passwords do not match."); if (!form.firstName.trim()) next.push("First name is required."); if (!form.lastName.trim()) next.push("Last name is required."); if (!/^\d{10}$/.test(form.phone)) next.push("Phone number must contain exactly 10 digits."); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.push("Invalid email address."); if (next.length) { setErrors(next); return; } setErrors([]); await onSubmit(form); }
  return <div className="auth-panel"><Card className="auth-card auth-card-wide"><Card.Body><div className="auth-kicker">PC SUPPORT</div><h3 className="mb-2">Create an account</h3><p className="text-muted mb-4">Set up your account to track service requests.</p><Form onSubmit={handleSubmit}><Row><Col md={6}><Form.Group className="mb-3"><Form.Label>First Name</Form.Label><Form.Control required name="firstName" value={form.firstName} onChange={handleChange} /></Form.Group></Col><Col md={6}><Form.Group className="mb-3"><Form.Label>Last Name</Form.Label><Form.Control required name="lastName" value={form.lastName} onChange={handleChange} /></Form.Group></Col></Row><Form.Group className="mb-3"><Form.Label>Phone</Form.Label><Form.Control required name="phone" value={form.phone} onChange={handleChange} /></Form.Group><Form.Group className="mb-3"><Form.Label>Email</Form.Label><Form.Control required type="email" name="email" value={form.email} onChange={handleChange} /></Form.Group><Form.Group className="mb-3"><Form.Label>Password</Form.Label><Form.Control required type="password" name="password" value={form.password} onChange={handleChange} /></Form.Group><Form.Group className="mb-4"><Form.Label>Confirm Password</Form.Label><Form.Control required type="password" name="confirmPassword" value={form.confirmPassword} onChange={handleChange} /></Form.Group>{errors.length > 0 && <Alert variant="danger" className="mb-3"><ul className="mb-0">{errors.map((error) => <li key={error}>{error}</li>)}</ul></Alert>}<Button type="submit" className="w-100" disabled={loading}>{loading ? "Creating Account..." : "Register"}</Button></Form></Card.Body></Card><div className="mb-3 pt-3"><Link to="/" className="text-decoration-none">← Go back to Home</Link></div></div>;
}
